'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('user',
      [
        {
          name: 'Cinthia Yamamoto',
          email: 'cinthia',
          password: '123',
          cpf: '12345678947',
          cellPhone: '11949794719',
          gender: 'F',
          description: 'Procurando por alguma menina para dividir o quarto comigo',
          question: 'Qual o nome da minha gata',
          answer: 'Bananinha',
          role: 'estudante',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Chrystian Santos',
          email: 'chrys',
          password: '123',
          cpf: '12345678977',
          cellPhone: '11949794719',
          gender: 'M',
          description: 'Buscando por um quarto em São Caetano do Sul',
          question: 'Qual o nome da minha gata',
          answer: 'Bananinha',
          role: 'estudante',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Victor Dourado',
          email: 'victor',
          password: '123',
          cpf: '98765432100',
          cellPhone: '11949794719',
          gender: 'M',
          description: 'Possuo imóveis disponíveis na região de São Caetano do Sul, próximos a faculdade Fatec São Caetano do Sul e ETEC Jorge Street',
          question: 'Qual o nome da minha gata',
          answer: 'Bananinha',
          role: 'proprietario',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Talita do Victor',
          email: 'talita@hotmail.com',
          password: '123',
          cpf: '74185296322',
          cellPhone: '11949794719',
          gender: 'F',
          description: 'Teste do teste',
          question: 'Qual o nome da minha gata',
          answer: 'Bananinha',
          role: 'estudante',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Isabella Ferreira',
          email: 'isa@hotmail.com',
          password: '123',
          cpf: '48555698725',
          cellPhone: '11949794719',
          gender: 'F',
          description: 'Possuo imóveis disponíveis na região de São Caetano do Sul, próximos a faculdade Fatec São Caetano do Sul e ETEC Jorge Street',
          question: 'Qual o nome do meu cachorro',
          answer: 'Lipe',
          role: 'proprietario',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Victor Costa',
          email: 'vicos_@hotmail.com',
          password: '123',
          cpf: '53648525684',
          cellPhone: '11949794719',
          gender: 'O',
          description: 'Buscando por imóveis próximos a Fatec São Caetano do Sul',
          question: 'O que mais amo nesse mundo?',
          answer: 'Meus priminhos',
          role: 'estudante',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Darci Yamamoto',
          email: 'darci@hotmail.com',
          password: '123',
          cpf: '74125896348',
          cellPhone: '11949794719',
          gender: 'F',
          description: 'Alugo imóveis na região da Vila Alpina, Vila Califórnia, Jardim Guairacá, quartos, casas em condomínios, apartamentos',
          question: 'O que mais amo nesse mundo?',
          answer: 'Meus priminhos',
          role: 'proprietario',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Marina Leite',
          email: 'ninaleite@hotmail.com',
          password: '123',
          cpf: '74569812355',
          cellPhone: '11949794719',
          gender: 'F',
          description: 'Estudo na Fatec São Caetano e busco por imóveis no ABC, além de uma companhia para dividir',
          question: 'O que mais amo nesse mundo?',
          answer: 'Meus priminhos',
          role: 'estudante',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Thais Costa',
          email: 'thacosta_@hotmail.com',
          password: '123',
          cpf: '65894235807',
          cellPhone: '11949794719',
          gender: 'F',
          description: 'Sou estudante de direito na USCS e procuro por imóveis para dividir na região do ABC',
          question: 'O que mais amo nesse mundo?',
          answer: 'Meus priminhos',
          role: 'estudante',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Milene Santana',
          email: 'milene@hotmail.com',
          password: '123',
          cpf: '74836524589',
          cellPhone: '11949794719',
          gender: 'M',
          description: 'Sou estudante de medicina na USCS e procuro por imóveis para dividir na região do ABC',
          question: 'O que mais amo nesse mundo?',
          answer: 'Meus priminhos',
          role: 'estudante',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Isis Corte',
          email: 'isiscorte@hotmail.com',
          password: '123',
          cpf: '98989351524',
          cellPhone: '11949794719',
          gender: 'F',
          description: 'Sou estudante de química na faculdade Mauá e procuro por quartos em São Caetano ou São Bernardo',
          question: 'O que mais amo nesse mundo?',
          answer: 'Meus priminhos',
          role: 'estudante',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Otavio Miquelotti',
          email: 'tavinho@hotmail.com',
          password: '123',
          cpf: '74512698547',
          cellPhone: '11949794719',
          gender: 'O',
          description: 'Procuro por pessoas da comunidade LGBT para compartilhar um apto, não conheço ninguém ainda pois sou da Praia Grande',
          question: 'O que mais amo nesse mundo?',
          answer: 'Meus priminhos',
          role: 'estudante',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Leonardo Souza',
          email: 'leozin@hotmail.com',
          password: '123',
          cpf: '45678912365',
          cellPhone: '11949794719',
          gender: 'M',
          description: 'Aos que procuram por imóveis para alugar, possuo imóveis e quartos individuais no ABC para alugar',
          question: 'O que mais amo nesse mundo?',
          answer: 'Meus priminhos',
          role: 'proprietario',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Henrique Guirelli',
          email: 'guirelli@hotmail.com',
          password: '123',
          cpf: '85469248533',
          cellPhone: '11949794719',
          gender: 'M',
          description: 'Já estou formado, sou de TI e busco por imóveis em São Caetano, onde trabalho',
          question: 'O que mais amo nesse mundo?',
          answer: 'Meus priminhos',
          role: 'estudante',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Henrique Poc',
          email: 'pocpoc@hotmail.com',
          password: '123',
          cpf: '65897421554',
          cellPhone: '11949794719',
          gender: 'O',
          description: 'Já estou formado, sou de TI e busco por imóveis em São Caetano, onde trabalho',
          question: 'O que mais amo nesse mundo?',
          answer: 'Meus priminhos',
          role: 'estudante',
          deleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]
    );
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('user', null, {});
  }
};
