const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/controller/userController.js']


const doc = {
    info: {
        version: "1.0.0",
        title: "Loftera API",
        description: "Documentation automatically generated by the <b>swagger.autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "user",
            "description": "Endpoints"
        }
    ],
    definitions: {
        user: {
            id: 10,
            name: "Jhon Doe",
            email: "jhon@doe.com",
            password:"2#dlsowjgmwpp28749sjfi",
            diplomas: [
                {
                    school: "XYZ University",
                    year: 2020,
                    completed: true,
                    internship: {
                        hours: 290,
                        location: "XYZ Company"
                    }
                }
            ]
        },
        AddUser: {
            $name: "Jhon Doe",
            $age: 29,
            about: ""
        }
    }
}


swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js');
});